### ISSUE TITLE
Identação dos atributos

### ISSUE THREAD

**Issue by LucasBLs** [brmodeloweb/brmodelo-site#1]
Boa noite,

Primeiramente, parabéns pelo projeto, seria interessante se pudesse identas os atributos.

**Comment by idmarjr** [comment]
Oi @LucasBLs !
Obrigado pela sugestão. 😄 
Você poderia dar mais detalhes sobre ela?
Se possível, adicionar alguns screenshots apontando o que mudaria com a sua sugestão implementada?

**Comment by idmarjr** [comment]
@LucasBLs 
Estou fechando essa issue por inatividade.  
Quando você puder fique a vontade pra adicionar mais detalhes e aí reabrimos o ticket.
