### ISSUE TITLE
boa tarde esqueci a senha do br modelo alguem sabe como recuperar

### ISSUE THREAD

**Issue by moshe613** [brmodeloweb/brmodelo-site#4]

**Comment by idmarjr** [comment]
Oi @moshe613 !

Me desculpe pela falha. Até hoje não havíamos implementado o módulo de recuperar a senha no *BRModeloWeb*.
Já [estamos trabalhando nisso](https://github.com/brmodeloweb/brmodelo-app/pull/165) e a opção deve estar disponível nas próximas semanas.

Se você precisar de acesso imediato, por favor envie um email para brmodeloweb@gmail.com solicitando a recuperação de senha.

**Comment by idmarjr** [comment]
Oi @moshe613 

Dia 22 de junho de 2021 [nós liberamos a feature de recuperação de senha](https://github.com/brmodeloweb/brmodelo-app/commit/08b65dc35be8829306d59b1487941b3665717025).
Agora você pode solicitar uma senha nova direto pelo https://app.brmodeloweb.com/#!/recovery.

Por conta disso vou fechar essa _issue_ mas caso você tenha alguma dificuldade pra redefinir sua senha, fique vontade pra comentar e reabrir esse ticket.
