### ISSUE TITLE
Melhorar Usabilidade

### ISSUE THREAD

**Issue by lmamede** [brmodeloweb/brmodelo-site#8]
Acho que seria legal a implementação de algumas ações que facilitem o uso, como por exemplo: 
- permitir alterar o texto dos elementos com um duplo clique no próprio elemento; 
- permitir o uso ctrl+c e ctrl+v para copiar e colar elementos;

Parabéns pelo projeto, comecei a usá-lo em aula como sugestão da professora e achei muito prático!

**Comment by idmarjr** [comment]
Oi @lmamede 
Obrigado pelas sugestões.

## Alterar nome dos elementos no canva

Essa é uma ótima sugestão mas pra te ser bem honesto acho que essa melhoria vai demorar um pouco pra ver a luz do dia por conta de outras algumas tarefas mais criticas que temos que terminar antes de chegar nisso. 😢 


## ctrl+c ctrl+v

Essa funcionalidade já está na fila. Vou atualizar esse ticket com novidades quando essa funcionalidade for pro ar: https://github.com/brmodeloweb/brmodelo-app/issues/332

**Comment by idmarjr** [comment]
Um update sobre suas sugestões.

- Fizemos algumas mudanças no comportamento da seleção de elementos.  Agora ao selecionar um elemento o foco do cursor muda automaticamente para o campo de _Nome_.
Isso ainda está em teste e talvez esse comportamento mude nos próximos meses.


- Os atalhos de teclado pra copiar e colar já estão no ar faz alguns meses :)
Se você quiser saber mais detalhes do funcionamento: [BRMW Docs - Copiando e colando elementos](https://docs.brmodeloweb.com/#/canvas-usage/README?id=copiando-e-colando-elementos)

---

Por hora vou fechar essa _issue_ . Se você quiser sugerir outras melhorias (Ou mesmo mais detalhes sobre essa), fica a vontade pra abrir outro ticket no https://github.com/brmodeloweb/brmodelo-app/issues/
